version: "3.7"

services:
  echoes:
    build: .
    command:
      - "--server-listen"
      - "0.0.0.0"
      - "--log-level"
      - "debug"
      - "--redis-host"
      - "redis"
    ports:
      - 8000:8000

  redis:
    image: redis:4-alpine
