name: Build and push to github packages
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Login
      run: docker login docker.pkg.github.com -u kklingenberg -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: >-
        docker build -t docker.pkg.github.com/kklingenberg/echoes/echoes:${GITHUB_REF}
                     --build-arg VERSION=${GITHUB_REF}
                     --build-arg SHA1=${GITHUB_SHA}
                     --build-arg BUILD=${GITHUB_RUN_ID}
                     .
    - name: Push
      run: docker push docker.pkg.github.com/kklingenberg/echoes/echoes:${GITHUB_REF}
