name: Build and push to registry

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Define version
      run: export VERSION=$(echo ${GITHUB_REF} | cut -d / -f 3)
    - name: Login
      run: docker login docker.pkg.github.com -u kklingenberg -p "${{ secrets.GITHUB_TOKEN }}"
    - name: Build
      run: >-
        docker build -t docker.pkg.github.com/kklingenberg/echoes/echoes:${VERSION}
                     --build-arg VERSION=${VERSION}
                     --build-arg SHA1=${GITHUB_SHA}
                     --build-arg BUILD=${GITHUB_RUN_ID}
    - name: Push
      run: docker push docker.pkg.github.com/kklingenberg/echoes/echoes:${VERSION}
